### ISSUE TITLE
Citação inline

### ISSUE THREAD

**Issue by marcieldeg** [quigonjeff/ifes8#5]
Boa noite,

Existe algum comando para citação inline? Como no exemplo a seguir:

_A fim de minimizar as limitações conhecidas nas Decision Trees, **Ho (1995)** propôs a Random Forest, ou Floresta Aleatória._

Se não houver um comando pré definido, sugiro a adição do mesmo.

`\newcommand{\citep}[1]{\citeauthoronline{#1} (\citeyear{#1})}`

**Comment by quigonjeff** [comment]
Sim. Todos os comando de citação do pacote `abntex2cite` estão disponíveis. Para citação no texto (inline) use o comando `\citeonline{key}`. Há também os comando `\citeyear`, `\citeauthor` e `\citeauthoronline`.
